// <auto-generated />
using System;
using Beblue.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Beblue.Repositories.Migrations
{
    [DbContext(typeof(BeblueContext))]
    [Migration("20191213152618_CreateInitial1")]
    partial class CreateInitial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("db")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Beblue.Domain.Entities.CashbackGenero", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DiaSemana");

                    b.Property<string>("GeneroId");

                    b.Property<double>("PercentualCashbackDia");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("CashbackGenero");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.Disco", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GeneroId");

                    b.Property<string>("Name");

                    b.Property<double>("Preco");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("Disco");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.Genero", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.Pedido", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClienteId");

                    b.Property<DateTime>("DataVenda");

                    b.Property<double>("TotalVenda");

                    b.Property<double>("ValorCashback");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiscoId");

                    b.Property<string>("PedidoId");

                    b.Property<double>("ValorCashBack");

                    b.HasKey("Id");

                    b.HasIndex("DiscoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItem");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.CashbackGenero", b =>
                {
                    b.HasOne("Beblue.Domain.Entities.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.Disco", b =>
                {
                    b.HasOne("Beblue.Domain.Entities.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Beblue.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("Beblue.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("Beblue.Domain.Entities.Disco", "Discos")
                        .WithMany()
                        .HasForeignKey("DiscoId");

                    b.HasOne("Beblue.Domain.Entities.Pedido", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoId");
                });
#pragma warning restore 612, 618
        }
    }
}
